### ISSUE TITLE
Is the quantitative result suit to the result reported in the paper?

### ISSUE THREAD

**Issue by minygd** [meder411/omnidepth-pytorch#1]
Hello! Thanks for your reimplement of the Omnidepth. There is a confusion for me, that is, is the quantitave result and qualitative result performs well just as the author stated in the paper?

Or is there any difference? Can you show some result of your model?

Thx!

**Comment by meder411** [comment]
These results are commensurate with those reported in the paper. If I have some time, I will run the eval script and post some specifics in the README.

**Comment by minygd** [comment]
Thank you. :)

By the way, I have some problem while running the codes.
I have installed OpenEXR by commend: pip install OpenEXR.
But it turned out I missed something:

> /.local/lib/python3.7/site-packages/OpenEXR.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZTIN7Iex_2_27BaseExcE

Can you give me some suggestions? Thx!

**Comment by meder411** [comment]
Use the conda environment as explained in the README

**Comment by minygd** [comment]
Yes,  I wanted to just set up a conda environment using the omnidepth.yml file in this repository, but the conda install informed me that there are some pkgs missing or can't be found. So I end up using conda and pip to install all the pkgs by hand.
