### ISSUE TITLE
Trained model for inference purpose and a reference

### ISSUE THREAD

**Issue by robbiedood** [meder411/omnidepth-pytorch#3]
Dear meder411,

Thanks for your implementation on OmniDpeth that would be very beneficial to the community.

I was wondering if you will also upload your trained network, e.g. checkpoint_latest.pth, so we could have a solid reference when using your implementation. It also helps people who would like to try inference simply.

Best,
-- Luke

**Comment by meder411** [comment]
Hi Luke,

I finally got around to converting the Caffe model from the Zioulis paper. If you still need it, `rectnet.pth` will give you the following results:

```
  Avg. Abs. Rel. Error: 0.0641
  Avg. Sq. Rel. Error: 0.0197
  Avg. Lin. RMS Error: 0.2297
  Avg. Log RMS Error: 0.0993
  Inlier D1: 0.9663
  Inlier D2: 0.9951
  Inlier D3: 0.9984
```

If you do a fresh git pull, everything should be there. I've updated the README too if you have any questions about using it.
