### ISSUE TITLE
Problems with channels when trying to create environment

### ISSUE THREAD

**Issue by StoneBones** [meder411/omnidepth-pytorch#4]
I keep running into an error while building with the .yml file where I get :

 TypeError: sequence item 0: expected str instance, Channel found

Has anyone else run into this? I've also attached a .txt of the error report below.

[yml_setup_error.txt](https://github.com/meder411/OmniDepth-PyTorch/files/4207466/yml_setup_error.txt)

**Comment by meder411** [comment]
Worst case, you should be able to just install the dependencies separately. I updated the README with the install commands.

**Comment by StoneBones** [comment]
Thanks so much for the quick response! I'll try this.
