### ISSUE TITLE
Question about Conv on Sphere

### ISSUE THREAD

**Issue by yanqswhu** [meder411/omnidepth-pytorch#5]
Hello! 

Thanks for your re-implement of the Omnidepth.

As you are the author of the Tangent-Images, how do you think about the OmniDepth's way to deal with the Spherical Convolution?   Which way is better in your mind, the Tangent-Images or the RectNet?

Thanks.

**Comment by meder411** [comment]
The Omnidepth approach has its merits, but it is still going to be limited by the fact that it uses equirectangular images. There’s a number of papers that have come out this past year that have shown significant improvements by using an icosahedral representation instead. As you are familiar with my ”[Tangent Images](https://arxiv.org/abs/1912.09390)” work, I’ll direct you to section 2.2 for an overview of those papers. 

Another paper of mine, [Mapped Convolutions](https://arxiv.org/abs/1906.11096), directly compares convolution on the icosahedron to the Omnidepth strategy and shows that the former works significantly better. Code for mapped convolutions can be found [here](https://github.com/meder411/MappedConvolutions) (docs could be better—improvements hopefully coming soon). 

I hope this answers your question.

**Comment by yanqswhu** [comment]
Thanks for your reply.

 Really appreciate your fantastic work, which is much easier to use than the "Spherical CNNs".
