### ISSUE TITLE
How to make inference on new equirectangular image

### ISSUE THREAD

**Issue by Sofiane23i** [meder411/omnidepth-pytorch#9]
Hello, 

As mentioned in the paper of OmniDepth: Dense Depth Estimation forIndoors Spherical Panoramas. in the result section (quantitative result), inference result are deployed using new equirectangular images. 

in this repositorty, test_omnidepth.py show performances using metrics. we would like to know if an inference script of the model exists or not.

Cordially

**Comment by meder411** [comment]
You can create a file list of the new inputs to run, and then modify `test_omnidepth.py` to just save the outputs of the network to some directory.
